# Generated by Django 4.0.5 on 2022-07-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_electric', models.BooleanField(default=False)),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('area_parking_id', models.IntegerField()),
            ],
        ),
    ]
