# Generated by Django 4.0.5 on 2022-08-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='area',
        ),
    ]
