# Generated by Django 4.0.5 on 2022-08-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0002_alter_contact_newsletter_searchparking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
