# Generated by Django 4.0.5 on 2022-08-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0002_rename_name_booking_code_remove_booking_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='final_price',
        ),
    ]
