# Generated by Django 4.0.5 on 2022-07-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0002_alter_area_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='Feedback', max_length=100),
        ),
    ]
