# Generated by Django 4.0.5 on 2022-07-24 00:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_park', '0003_feedback_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='car_park.booking'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_by',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
